name: ARM64-Native

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: arm64

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'liberica'
          java-version: '17'
      #Run Tests
      - name: Run Tests
        run: ./mvnw -Pnative test
      #Build Image
      - name: Build Image
        run: ./mvnw -Pnative -DskipTests spring-boot:build-image